-- data/pg-migrations/0007_restore_curated_fields.sql
--
-- Restores four curated columns that the Postgres redesign's
-- corpus.entities table (0001_north_star.sql) never carried forward:
-- outlets' founded/circulation_note, subreddits' subscriber_count_proxy,
-- and officials'/accounts' account_type. All four existed in the retired
-- YAML registries (data/news_outlets.yaml, data/major_subreddits.yaml,
-- data/known_political_x_accounts.yaml) and were dropped when
-- 0002_entity_registry_seed.sql seeded the table -- the seed only carried
-- forward role_title/term_start/owner/source_citation/lean/lean_source,
-- not the reach-proxy or account-classification fields the pre-Postgres
-- UI's EntityProfile rendered.
--
-- Nullable and kind-scoped, matching the role_title/owner convention
-- already established on this table: founded/circulation_note only
-- apply to kind='outlet'; subscriber_count_proxy only to kind='subreddit';
-- account_type only to kind='official'/'collective' rows shaped like an
-- individual X account (the executive-branch entries below).
--
-- This is a ONE-TIME backfill from the frozen YAML registries at git tag
-- pre-cutover-main. Curation continues DB-native (direct SQL edits)
-- afterward -- no sync process, the same convention already established
-- for role_title/owner/source_citation etc. in 0001_north_star.sql and
-- seeded once by 0002_entity_registry_seed.sql.
--
-- Row counts backfilled below (generated by a one-off script parsing the
-- frozen YAML, see docs/audit-trail/analysis/2026-07-27-entity-profile-restoration.md):
--   founded/circulation_note   21 outlets   (all of data/news_outlets.yaml)
--   subscriber_count_proxy     15 subreddits (all of data/major_subreddits.yaml)
--   account_type               31 accounts  (see note below -- NOT all 583
--                              handles in known_political_x_accounts.yaml
--                              carry an account_type field)
--
-- SCHEMA DISCREPANCY: the source YAML does not have a flat handle ->
-- account_type mapping. Only the 12 executive_branch entries nest a
-- per-handle `accounts: [{handle, account_type}, ...]` list (31 handles
-- total: official/official_role/personal/personal_political/institutional).
-- The 437 House members, 100 Senate members, and 15 affiliated-collective
-- entries carry a bare `handle` field with no account_type at all --
-- fabricating one for those would violate the never-fabricate invariant,
-- so this migration only backfills account_type where the YAML actually
-- states it.
--
-- Applies cleanly on top of 0001_north_star.sql -- 0006_clustering_embedding_failures.sql.
-- Not idempotent by itself -- same one-shot-apply convention as every other
-- file in this directory (the Go migration runner tracks the applied
-- version in ops.schema_migrations, so this file is never replayed against
-- an already-migrated database).

ALTER TABLE corpus.entities
    ADD COLUMN founded SMALLINT,
    ADD COLUMN circulation_note TEXT,
    ADD COLUMN subscriber_count_proxy TEXT,
    ADD COLUMN account_type TEXT;

COMMENT ON COLUMN corpus.entities.founded IS 'Curated, hand-editable, kind-scoped-nullable: the outlet''s founding year. Meaningful only where kind=''outlet''; NULL otherwise. Backfilled once from data/news_outlets.yaml at tag pre-cutover-main; curated directly thereafter.';
COMMENT ON COLUMN corpus.entities.circulation_note IS 'Curated, hand-editable, kind-scoped-nullable: a reach proxy (NOT validated traffic -- media-analysis labeling rule) for the outlet. Meaningful only where kind=''outlet''; NULL otherwise. Backfilled once from data/news_outlets.yaml at tag pre-cutover-main; curated directly thereafter.';
COMMENT ON COLUMN corpus.entities.subscriber_count_proxy IS 'Curated, hand-editable, kind-scoped-nullable: a reach proxy (NOT validated traffic) for the subreddit. Meaningful only where kind=''subreddit''; NULL otherwise. Backfilled once from data/major_subreddits.yaml at tag pre-cutover-main; curated directly thereafter.';
COMMENT ON COLUMN corpus.entities.account_type IS 'Curated, hand-editable, kind-scoped-nullable: the X account''s classification (official / official_role / personal / personal_political / institutional / sampled). Meaningful only where kind IN (''official'', ''collective'') and the row is shaped like an individual account; NULL otherwise. Backfilled once from data/known_political_x_accounts.yaml at tag pre-cutover-main -- only the 31 handles that YAML actually classified (see header note); curated directly thereafter.';

-- Outlets: founded, circulation_note (21 rows, all of news_outlets.yaml).
UPDATE corpus.entities SET founded = 1846, circulation_note = 'Wire service syndicated to thousands of outlets (no direct subscriber count)' WHERE entity_key = 'apnews.com';
UPDATE corpus.entities SET founded = 2017, circulation_note = 'Newsletter-led distribution; ~5M newsletter subscribers (proxy)' WHERE entity_key = 'axios.com';
UPDATE corpus.entities SET founded = 1922, circulation_note = 'Major global outlet; US-facing traffic large but not separately reported (proxy)' WHERE entity_key = 'bbc.com';
UPDATE corpus.entities SET founded = 1990, circulation_note = '~350k paying terminal subscribers + large free digital reach (proxy)' WHERE entity_key = 'bloomberg.com';
UPDATE corpus.entities SET founded = 2007, circulation_note = 'Digital only; reach concentrated on the populist right (proxy)' WHERE entity_key = 'breitbart.com';
UPDATE corpus.entities SET founded = 1927, circulation_note = 'Network broadcast + large free digital reach (proxy)' WHERE entity_key = 'cbsnews.com';
UPDATE corpus.entities SET founded = 1980, circulation_note = '~500k-1M average prime-time viewers (proxy)' WHERE entity_key = 'cnn.com';
UPDATE corpus.entities SET founded = 1996, circulation_note = '~2M average prime-time viewers (proxy)' WHERE entity_key = 'foxnews.com';
UPDATE corpus.entities SET founded = 1996, circulation_note = '~1M average prime-time viewers (proxy)' WHERE entity_key = 'msnbc.com';
UPDATE corpus.entities SET founded = 1955, circulation_note = 'Opinion magazine + digital; reach is professional-conservative (proxy)' WHERE entity_key = 'nationalreview.com';
UPDATE corpus.entities SET founded = 1970, circulation_note = '~50M weekly radio listeners (proxy)' WHERE entity_key = 'npr.org';
UPDATE corpus.entities SET founded = 1851, circulation_note = '~10M paid digital subscribers (proxy)' WHERE entity_key = 'nytimes.com';
UPDATE corpus.entities SET founded = 2007, circulation_note = 'Political/policy-insider audience; free digital + paid Pro tier' WHERE entity_key = 'politico.com';
UPDATE corpus.entities SET founded = 1851, circulation_note = 'Wire service + reuters.com digital (no direct subscriber count)' WHERE entity_key = 'reuters.com';
UPDATE corpus.entities SET founded = 1857, circulation_note = '~1M paid subscribers (proxy)' WHERE entity_key = 'theatlantic.com';
UPDATE corpus.entities SET founded = 2013, circulation_note = 'Digital only; reach is conservative-activist (proxy)' WHERE entity_key = 'thefederalist.com';
UPDATE corpus.entities SET founded = 1994, circulation_note = 'Large free digital reach; no paywall (proxy)' WHERE entity_key = 'thehill.com';
UPDATE corpus.entities SET founded = 2014, circulation_note = 'Digital only; reach is left-investigative audience (proxy)' WHERE entity_key = 'theintercept.com';
UPDATE corpus.entities SET founded = 1982, circulation_note = '~1.7M print + digital subscribers (proxy)' WHERE entity_key = 'usatoday.com';
UPDATE corpus.entities SET founded = 1877, circulation_note = '~2.5M paid digital subscribers (proxy)' WHERE entity_key = 'washingtonpost.com';
UPDATE corpus.entities SET founded = 1889, circulation_note = '~4M paid subscribers (proxy)' WHERE entity_key = 'wsj.com';

-- Subreddits: subscriber_count_proxy (15 rows, all of major_subreddits.yaml).
UPDATE corpus.entities SET subscriber_count_proxy = '~75k' WHERE entity_key = 'askaliberal';
UPDATE corpus.entities SET subscriber_count_proxy = '~55k' WHERE entity_key = 'askconservatives';
UPDATE corpus.entities SET subscriber_count_proxy = '~1.3M' WHERE entity_key = 'conservative';
UPDATE corpus.entities SET subscriber_count_proxy = '~550k' WHERE entity_key = 'democrats';
UPDATE corpus.entities SET subscriber_count_proxy = '~1M' WHERE entity_key = 'geopolitics';
UPDATE corpus.entities SET subscriber_count_proxy = '~480k' WHERE entity_key = 'libertarian';
UPDATE corpus.entities SET subscriber_count_proxy = '~90k' WHERE entity_key = 'moderatepolitics';
UPDATE corpus.entities SET subscriber_count_proxy = '~230k' WHERE entity_key = 'neoliberal';
UPDATE corpus.entities SET subscriber_count_proxy = '~180k' WHERE entity_key = 'neutralpolitics';
UPDATE corpus.entities SET subscriber_count_proxy = '~28M' WHERE entity_key = 'news';
UPDATE corpus.entities SET subscriber_count_proxy = '~2M' WHERE entity_key = 'politicaldiscussion';
UPDATE corpus.entities SET subscriber_count_proxy = '~2.3M' WHERE entity_key = 'politicalhumor';
UPDATE corpus.entities SET subscriber_count_proxy = '~8M' WHERE entity_key = 'politics';
UPDATE corpus.entities SET subscriber_count_proxy = '~200k' WHERE entity_key = 'republican';
UPDATE corpus.entities SET subscriber_count_proxy = '~35M' WHERE entity_key = 'worldnews';

-- Accounts: account_type (31 rows -- executive_branch entries only, see
-- the SCHEMA DISCREPANCY note above). entity_key with no matching row
-- simply updates 0 rows, which is fine and expected.
UPDATE corpus.entities SET account_type = 'official_role' WHERE entity_key = 'agpambondi';
UPDATE corpus.entities SET account_type = 'institutional' WHERE entity_key = 'cia';
UPDATE corpus.entities SET account_type = 'official_role' WHERE entity_key = 'ciadirector';
UPDATE corpus.entities SET account_type = 'personal/official' WHERE entity_key = 'dagtoddblanche';
UPDATE corpus.entities SET account_type = 'personal/official' WHERE entity_key = 'dciaratcliffe';
UPDATE corpus.entities SET account_type = 'institutional' WHERE entity_key = 'deptofwar';
UPDATE corpus.entities SET account_type = 'institutional' WHERE entity_key = 'dhsgov';
UPDATE corpus.entities SET account_type = 'official_role' WHERE entity_key = 'dnigabbard';
UPDATE corpus.entities SET account_type = 'institutional' WHERE entity_key = 'fbi';
UPDATE corpus.entities SET account_type = 'official_role' WHERE entity_key = 'fbidirectorkash';
UPDATE corpus.entities SET account_type = 'institutional' WHERE entity_key = 'hhsgov';
UPDATE corpus.entities SET account_type = 'personal/political' WHERE entity_key = 'jdvance';
UPDATE corpus.entities SET account_type = 'personal' WHERE entity_key = 'kash_patel';
UPDATE corpus.entities SET account_type = 'personal/official' WHERE entity_key = 'kristinoem';
UPDATE corpus.entities SET account_type = 'personal/political' WHERE entity_key = 'marcorubio';
UPDATE corpus.entities SET account_type = 'institutional' WHERE entity_key = 'odnigov';
UPDATE corpus.entities SET account_type = 'personal/official' WHERE entity_key = 'petehegseth';
UPDATE corpus.entities SET account_type = 'official' WHERE entity_key = 'potus';
UPDATE corpus.entities SET account_type = 'personal/political' WHERE entity_key = 'realdonaldtrump';
UPDATE corpus.entities SET account_type = 'personal/political' WHERE entity_key = 'robertkennedyjr';
UPDATE corpus.entities SET account_type = 'official_role' WHERE entity_key = 'sec_noem';
UPDATE corpus.entities SET account_type = 'official_role' WHERE entity_key = 'seckennedy';
UPDATE corpus.entities SET account_type = 'official_role' WHERE entity_key = 'secrubio';
UPDATE corpus.entities SET account_type = 'official_role' WHERE entity_key = 'secscottbessent';
UPDATE corpus.entities SET account_type = 'official_role' WHERE entity_key = 'secwar';
UPDATE corpus.entities SET account_type = 'institutional' WHERE entity_key = 'statedept';
UPDATE corpus.entities SET account_type = 'institutional' WHERE entity_key = 'thejusticedept';
UPDATE corpus.entities SET account_type = 'personal' WHERE entity_key = 'tulsigabbard';
UPDATE corpus.entities SET account_type = 'institutional' WHERE entity_key = 'ustreasury';
UPDATE corpus.entities SET account_type = 'official' WHERE entity_key = 'vp';
UPDATE corpus.entities SET account_type = 'institutional' WHERE entity_key = 'whitehouse';
