"""
Reporting models package.

Provides dataclasses for structured API responses.
"""

from analysis.src.reporting.models.aggregator_models import (
    OutletProfile,
    SentimentOverview,
    SentimentDistribution,
    PlatformSentiment,
    TopicSentiment,
    ClassificationSample,
    TimeWindowSentiment,
    DayOfWeekSentiment,
    EntitySentimentItem,
    PublicSentimentResult,
    FavorabilityOverall,
    TrendPoint,
    PlatformFavorability,
    PollingSocialComparison,
    GOPFavorabilityResult,
    BotEntityItem,
    BotOverview,
    EntityToneMover,
    FavorabilityMover,
    MoversResult,
    FlaggedExample,
    NarrativeAmplification,
    CoordinationStats,
    BehavioralSignals,
    BotActivityData,
    NarrativeSummary,
)

__all__ = [
    "OutletProfile",
    "SentimentOverview",
    "SentimentDistribution",
    "PlatformSentiment",
    "TopicSentiment",
    "ClassificationSample",
    "TimeWindowSentiment",
    "DayOfWeekSentiment",
    "EntitySentimentItem",
    "PublicSentimentResult",
    "FavorabilityOverall",
    "TrendPoint",
    "PlatformFavorability",
    "PollingSocialComparison",
    "GOPFavorabilityResult",
    "BotEntityItem",
    "BotOverview",
    "EntityToneMover",
    "FavorabilityMover",
    "MoversResult",
    "FlaggedExample",
    "NarrativeAmplification",
    "CoordinationStats",
    "BehavioralSignals",
    "BotActivityData",
    "NarrativeSummary",
]
