// <auto-generated />
using CivicLens.Infrastructure.Collection;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CivicLens.Infrastructure.Collection.Migrations
{
    [DbContext(typeof(CollectionAttemptDbContext))]
    [Migration("20261008190000_DurableEvidenceProcessing")]
    partial class DurableEvidenceProcessing
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);
            modelBuilder.Entity("CivicLens.Infrastructure.Collection.Processing.PersistedEvidenceProcessingRow", b =>
            {
                b.Property<string>("JobId").IsRequired().HasMaxLength(128).HasColumnType("character varying(128)").HasColumnName("job_id");
                b.Property<string>("AttemptId").IsRequired().HasMaxLength(128).HasColumnType("character varying(128)").HasColumnName("attempt_id");
                b.Property<string>("SourceId").IsRequired().HasMaxLength(128).HasColumnType("character varying(128)").HasColumnName("source_id");
                b.Property<string>("RequestedUrl").IsRequired().HasMaxLength(4096).HasColumnType("character varying(4096)").HasColumnName("requested_url");
                b.Property<long?>("ObservedAtUtcTicks").HasColumnType("bigint").HasColumnName("observed_at_utc_ticks");
                b.Property<string>("Stage").IsRequired().HasColumnType("text").HasColumnName("stage");
                b.Property<string>("Status").IsRequired().HasColumnType("text").HasColumnName("status");
                b.Property<string>("LeaseToken").HasMaxLength(64).HasColumnType("character varying(64)").HasColumnName("lease_token");
                b.Property<long>("Fence").HasColumnType("bigint").HasColumnName("fence");
                b.Property<long?>("LeaseExpiresAt").HasColumnType("bigint").HasColumnName("lease_expires_at");
                b.Property<int>("Attempts").HasColumnType("integer").HasColumnName("attempts");
                b.Property<long?>("RetryAt").HasColumnType("bigint").HasColumnName("retry_at");
                b.Property<string>("ExtractionId").HasMaxLength(64).HasColumnType("character varying(64)").HasColumnName("extraction_id");
                b.Property<string>("ComparisonId").HasMaxLength(64).HasColumnType("character varying(64)").HasColumnName("comparison_id");
                b.Property<string>("Outcome").HasColumnType("text").HasColumnName("outcome");
                b.Property<string>("ErrorCode").HasMaxLength(128).HasColumnType("character varying(128)").HasColumnName("error_code");
                b.Property<int>("AdmittedCount").HasColumnType("integer").HasColumnName("admitted_count");
                b.Property<int>("DeferredCount").HasColumnType("integer").HasColumnName("deferred_count");
                b.Property<int>("DuplicateCount").HasColumnType("integer").HasColumnName("duplicate_count");
                b.HasKey("JobId", "AttemptId");
                b.HasIndex("JobId", "Stage", "Status");
                b.HasIndex("Status", "ObservedAtUtcTicks", "AttemptId", "JobId");
                b.ToTable("evidence_processing", t =>
                {
                    t.HasCheckConstraint("ck_evidence_processing_fence", "fence >= 0 AND attempts >= 0");
                    t.HasCheckConstraint("ck_evidence_processing_lease", "(lease_token IS NULL) = (lease_expires_at IS NULL)");
                    t.HasCheckConstraint("ck_evidence_processing_stage", "stage IN ('Preparation','Extraction','Comparison','Complete')");
                    t.HasCheckConstraint("ck_evidence_processing_status", "status IN ('Pending','Running','RetryWaiting','Succeeded','Blocked','Failed')");
                    t.HasCheckConstraint("ck_evidence_processing_evidence_ids", "(extraction_id IS NULL OR extraction_id ~ '^[0-9a-f]{64}$') AND (comparison_id IS NULL OR comparison_id ~ '^[0-9a-f]{64}$')");
                    t.HasCheckConstraint("ck_evidence_processing_counts", "admitted_count >= 0 AND deferred_count >= 0 AND duplicate_count >= 0");
                });
            });
#pragma warning restore 612, 618
        }
    }
}
