// <auto-generated />
using CivicLens.Infrastructure.Collection;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CivicLens.Infrastructure.Collection.Migrations
{
    [DbContext(typeof(CollectionAttemptDbContext))]
    partial class CollectionAttemptDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CivicLens.Infrastructure.Collection.Persistence.AttemptRow", b =>
                {
                    b.Property<string>("AttemptId")
                        .HasColumnType("text")
                        .HasColumnName("attempt_id");

                    b.Property<string>("CaptureSha256")
                        .HasColumnType("text")
                        .HasColumnName("capture_sha256");

                    b.Property<string>("FailureCode")
                        .HasColumnType("text")
                        .HasColumnName("failure_code");

                    b.Property<string>("FinalUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("final_url");

                    b.Property<bool>("HasResponse")
                        .HasColumnType("boolean")
                        .HasColumnName("has_response");

                    b.Property<bool>("HasSentValidators")
                        .HasColumnType("boolean")
                        .HasColumnName("has_sent_validators");

                    b.Property<long>("ObservedAtUtcTicks")
                        .HasColumnType("bigint")
                        .HasColumnName("observed_at_utc_ticks");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("outcome");

                    b.Property<string>("PriorCaptureAttemptId")
                        .HasColumnType("text")
                        .HasColumnName("prior_capture_attempt_id");

                    b.Property<string>("PriorCaptureSha256")
                        .HasColumnType("text")
                        .HasColumnName("prior_capture_sha256");

                    b.Property<string>("RequestedUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("requested_url");

                    b.PrimitiveCollection<string[]>("ResponseContentEncodings")
                        .HasColumnType("text[]")
                        .HasColumnName("response_content_encodings");

                    b.Property<string>("ResponseContentType")
                        .HasColumnType("text")
                        .HasColumnName("response_content_type");

                    b.Property<string>("ResponseETag")
                        .HasColumnType("text")
                        .HasColumnName("response_etag");

                    b.Property<long?>("ResponseLastModifiedUtcTicks")
                        .HasColumnType("bigint")
                        .HasColumnName("response_last_modified_utc_ticks");

                    b.Property<int?>("ResponseStatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("response_status_code");

                    b.Property<long?>("RetryDelayTicks")
                        .HasColumnType("bigint")
                        .HasColumnName("retry_delay_ticks");

                    b.Property<string>("SentETag")
                        .HasColumnType("text")
                        .HasColumnName("sent_etag");

                    b.Property<long?>("SentLastModifiedUtcTicks")
                        .HasColumnType("bigint")
                        .HasColumnName("sent_last_modified_utc_ticks");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_id");

                    b.HasKey("AttemptId");

                    b.HasIndex("CaptureSha256")
                        .HasDatabaseName("ix_collection_attempts_capture");

                    b.HasIndex("PriorCaptureAttemptId")
                        .HasDatabaseName("ix_collection_attempts_prior_capture_link");

                    b.HasIndex("AttemptId", "CaptureSha256")
                        .IsUnique()
                        .HasDatabaseName("ux_collection_attempts_id_capture");

                    b.HasIndex("SourceId", "ObservedAtUtcTicks", "AttemptId")
                        .HasDatabaseName("ix_collection_attempts_prior_capture")
                        .HasFilter("outcome = 'captured'");

                    b.ToTable("collection_attempts", null, t =>
                        {
                            t.HasCheckConstraint("ck_collection_attempts_identity", "length(btrim(attempt_id)) > 0 AND length(btrim(source_id)) > 0 AND length(btrim(requested_url)) > 0 AND length(btrim(final_url)) > 0");

                            t.HasCheckConstraint("ck_collection_attempts_observed_ticks", "observed_at_utc_ticks BETWEEN 0 AND 3155378975999999999");

                            t.HasCheckConstraint("ck_collection_attempts_outcome", "(outcome = 'captured' AND has_response AND response_status_code IS NOT NULL AND response_status_code = 200 AND capture_sha256 IS NOT NULL AND failure_code IS NULL AND retry_delay_ticks IS NULL AND prior_capture_attempt_id IS NULL AND prior_capture_sha256 IS NULL)\nOR (outcome = 'notModified' AND has_response AND has_sent_validators AND response_status_code IS NOT NULL AND response_status_code = 304 AND capture_sha256 IS NULL AND failure_code IS NULL AND retry_delay_ticks IS NULL)\nOR (outcome = 'failed' AND failure_code IS NOT NULL AND retry_delay_ticks IS NULL AND capture_sha256 IS NULL AND prior_capture_attempt_id IS NULL AND prior_capture_sha256 IS NULL)\nOR (outcome = 'deferred' AND failure_code IS NOT NULL AND capture_sha256 IS NULL AND prior_capture_attempt_id IS NULL AND prior_capture_sha256 IS NULL)");

                            t.HasCheckConstraint("ck_collection_attempts_prior_outcome", "prior_capture_attempt_id IS NULL OR (outcome = 'notModified' AND prior_capture_attempt_id <> attempt_id)");

                            t.HasCheckConstraint("ck_collection_attempts_prior_pair", "(prior_capture_attempt_id IS NULL) = (prior_capture_sha256 IS NULL)");

                            t.HasCheckConstraint("ck_collection_attempts_response", "(has_response AND response_status_code IS NOT NULL AND response_status_code BETWEEN 100 AND 599 AND response_content_encodings IS NOT NULL AND array_position(response_content_encodings, NULL) IS NULL)\nOR (NOT has_response AND response_status_code IS NULL AND response_etag IS NULL AND response_last_modified_utc_ticks IS NULL AND response_content_type IS NULL AND response_content_encodings IS NULL)");

                            t.HasCheckConstraint("ck_collection_attempts_response_ticks", "response_last_modified_utc_ticks IS NULL OR response_last_modified_utc_ticks BETWEEN 0 AND 3155378975999999999");

                            t.HasCheckConstraint("ck_collection_attempts_retry_ticks", "retry_delay_ticks IS NULL OR retry_delay_ticks >= 0");

                            t.HasCheckConstraint("ck_collection_attempts_sent_ticks", "sent_last_modified_utc_ticks IS NULL OR sent_last_modified_utc_ticks BETWEEN 0 AND 3155378975999999999");

                            t.HasCheckConstraint("ck_collection_attempts_validators", "(has_sent_validators OR (sent_etag IS NULL AND sent_last_modified_utc_ticks IS NULL))");
                        });
                });

            modelBuilder.Entity("CivicLens.Infrastructure.Collection.Persistence.CaptureRow", b =>
                {
                    b.Property<string>("Sha256")
                        .HasColumnType("text")
                        .HasColumnName("sha256");

                    b.Property<long>("ByteLength")
                        .HasColumnType("bigint")
                        .HasColumnName("byte_length");

                    b.HasKey("Sha256");

                    b.ToTable("collection_captures", null, t =>
                        {
                            t.HasCheckConstraint("ck_collection_captures_byte_length", "byte_length >= 0");

                            t.HasCheckConstraint("ck_collection_captures_sha256", "sha256 ~ '^[0-9a-f]{64}$'");
                        });
                });

            modelBuilder.Entity("CivicLens.Infrastructure.Collection.Persistence.AttemptRow", b =>
                {
                    b.HasOne("CivicLens.Infrastructure.Collection.Persistence.CaptureRow", null)
                        .WithMany()
                        .HasForeignKey("CaptureSha256")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CivicLens.Infrastructure.Collection.Persistence.AttemptRow", null)
                        .WithMany()
                        .HasForeignKey("PriorCaptureAttemptId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
