// <auto-generated />
using CivicLens.Infrastructure.Collection;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CivicLens.Infrastructure.Collection.Migrations
{
    [DbContext(typeof(CollectionAttemptDbContext))]
    partial class CollectionAttemptDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CivicLens.Infrastructure.Collection.Discovery.DiscoveryAdmissionBatchRow", b =>
                {
                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("AttemptId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("attempt_id");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("bigint")
                        .HasColumnName("created_at");

                    b.Property<string>("InputJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("input_json");

                    b.Property<string>("ResultJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("result_json");

                    b.HasKey("IdempotencyKey");

                    b.HasIndex("AttemptId");

                    b.ToTable("collection_admission_batches", (string)null);
                });

            modelBuilder.Entity("CivicLens.Infrastructure.Collection.Discovery.DiscoveryCandidateJobRow", b =>
                {
                    b.Property<string>("CandidateHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("candidate_hash");

                    b.Property<string>("JobId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("job_id");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_id");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)")
                        .HasColumnName("url");

                    b.HasKey("CandidateHash");

                    b.HasIndex("JobId");

                    b.ToTable("collection_candidate_jobs", (string)null);
                });

            modelBuilder.Entity("CivicLens.Infrastructure.Collection.Discovery.DiscoveryRow", b =>
                {
                    b.Property<string>("AttemptId")
                        .HasColumnType("text")
                        .HasColumnName("attempt_id");

                    b.Property<string>("DiscoveryJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("discovery_json");

                    b.Property<string>("RequestJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("request_json");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_id");

                    b.HasKey("AttemptId");

                    b.ToTable("collection_discoveries", (string)null);
                });

            modelBuilder.Entity("CivicLens.Infrastructure.Collection.Jobs.Persistence.CollectorSlotRow", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("AttemptId")
                        .HasColumnType("character varying(128)")
                        .HasColumnName("attempt_id");

                    b.Property<long?>("ExpiresAt")
                        .HasColumnType("bigint")
                        .HasColumnName("expires_at");

                    b.Property<long>("Fence")
                        .HasColumnType("bigint")
                        .HasColumnName("fence");

                    b.Property<string>("JobId")
                        .HasColumnType("character varying(128)")
                        .HasColumnName("job_id");

                    b.Property<string>("Token")
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.HasKey("Id");

                    b.HasIndex("AttemptId");

                    b.HasIndex("JobId");

                    b.ToTable("collection_collector_slot", null, t =>
                        {
                            t.HasCheckConstraint("ck_collector_lease", "(token IS NULL AND expires_at IS NULL AND job_id IS NULL AND attempt_id IS NULL) OR (token IS NOT NULL AND expires_at IS NOT NULL AND job_id IS NOT NULL AND attempt_id IS NOT NULL)");

                            t.HasCheckConstraint("ck_collector_singleton", "id = 1");
                        });
                });

            modelBuilder.Entity("CivicLens.Infrastructure.Collection.Jobs.Persistence.JobAttemptRow", b =>
                {
                    b.Property<string>("AttemptId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("attempt_id");

                    b.Property<long?>("CompletedAt")
                        .HasColumnType("bigint")
                        .HasColumnName("completed_at");

                    b.Property<string>("JobId")
                        .IsRequired()
                        .HasColumnType("character varying(128)")
                        .HasColumnName("job_id");

                    b.Property<string>("RequestJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("request_json");

                    b.Property<string>("ResolutionJson")
                        .HasColumnType("text")
                        .HasColumnName("resolution_json");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.Property<long>("StartedAt")
                        .HasColumnType("bigint")
                        .HasColumnName("started_at");

                    b.HasKey("AttemptId");

                    b.HasIndex("JobId")
                        .IsUnique()
                        .HasFilter("resolution_json IS NULL");

                    b.HasIndex("JobId", "Sequence")
                        .IsUnique();

                    b.ToTable("collection_job_attempts", null, t =>
                        {
                            t.HasCheckConstraint("ck_job_attempt_resolution", "(resolution_json IS NULL) = (completed_at IS NULL)");

                            t.HasCheckConstraint("ck_job_attempt_sequence", "sequence > 0");
                        });
                });

            modelBuilder.Entity("CivicLens.Infrastructure.Collection.Jobs.Persistence.JobOriginRow", b =>
                {
                    b.Property<string>("Origin")
                        .HasColumnType("text")
                        .HasColumnName("origin");

                    b.Property<long>("NotBefore")
                        .HasColumnType("bigint")
                        .HasColumnName("not_before");

                    b.Property<string>("UnresolvedAttemptId")
                        .HasColumnType("character varying(128)")
                        .HasColumnName("unresolved_attempt_id");

                    b.HasKey("Origin");

                    b.HasIndex("UnresolvedAttemptId");

                    b.ToTable("collection_job_origins", (string)null);
                });

            modelBuilder.Entity("CivicLens.Infrastructure.Collection.Jobs.Persistence.JobRow", b =>
                {
                    b.Property<string>("JobId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("job_id");

                    b.Property<bool>("CancellationRequested")
                        .HasColumnType("boolean")
                        .HasColumnName("cancellation_requested");

                    b.Property<long>("ChargedBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("charged_bytes");

                    b.Property<int>("ChargedRequests")
                        .HasColumnType("integer")
                        .HasColumnName("charged_requests");

                    b.Property<int>("ChargedSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("charged_seconds");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("bigint")
                        .HasColumnName("created_at");

                    b.Property<string>("DefinitionJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("definition_json");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("idempotency_key");

                    b.Property<long?>("LeaseExpiresAt")
                        .HasColumnType("bigint")
                        .HasColumnName("lease_expires_at");

                    b.Property<long>("LeaseFence")
                        .HasColumnType("bigint")
                        .HasColumnName("lease_fence");

                    b.Property<string>("LeaseToken")
                        .HasColumnType("text")
                        .HasColumnName("lease_token");

                    b.Property<long?>("RetryAt")
                        .HasColumnType("bigint")
                        .HasColumnName("retry_at");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.HasKey("JobId");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("CreatedAt", "JobId");

                    b.ToTable("collection_jobs", null, t =>
                        {
                            t.HasCheckConstraint("ck_job_budget", "charged_requests >= 0 AND charged_bytes >= 0 AND charged_seconds >= 0");

                            t.HasCheckConstraint("ck_job_lease", "(lease_token IS NULL) = (lease_expires_at IS NULL)");

                            t.HasCheckConstraint("ck_job_state", "state IN ('Pending','Running','WaitingToRetry','Succeeded','Failed','Cancelled')");
                        });
                });

            modelBuilder.Entity("CivicLens.Infrastructure.Collection.Persistence.AttemptRow", b =>
                {
                    b.Property<string>("AttemptId")
                        .HasColumnType("text")
                        .HasColumnName("attempt_id");

                    b.Property<string>("CaptureSha256")
                        .HasColumnType("text")
                        .HasColumnName("capture_sha256");

                    b.Property<string>("FailureCode")
                        .HasColumnType("text")
                        .HasColumnName("failure_code");

                    b.Property<string>("FinalUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("final_url");

                    b.Property<bool>("HasResponse")
                        .HasColumnType("boolean")
                        .HasColumnName("has_response");

                    b.Property<bool>("HasSentValidators")
                        .HasColumnType("boolean")
                        .HasColumnName("has_sent_validators");

                    b.Property<long>("ObservedAtUtcTicks")
                        .HasColumnType("bigint")
                        .HasColumnName("observed_at_utc_ticks");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("outcome");

                    b.Property<string>("PriorCaptureAttemptId")
                        .HasColumnType("text")
                        .HasColumnName("prior_capture_attempt_id");

                    b.Property<string>("PriorCaptureSha256")
                        .HasColumnType("text")
                        .HasColumnName("prior_capture_sha256");

                    b.Property<string>("RequestedUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("requested_url");

                    b.PrimitiveCollection<string[]>("ResponseContentEncodings")
                        .HasColumnType("text[]")
                        .HasColumnName("response_content_encodings");

                    b.Property<string>("ResponseContentType")
                        .HasColumnType("text")
                        .HasColumnName("response_content_type");

                    b.Property<string>("ResponseETag")
                        .HasColumnType("text")
                        .HasColumnName("response_etag");

                    b.Property<long?>("ResponseLastModifiedUtcTicks")
                        .HasColumnType("bigint")
                        .HasColumnName("response_last_modified_utc_ticks");

                    b.Property<int?>("ResponseStatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("response_status_code");

                    b.Property<long?>("RetryDelayTicks")
                        .HasColumnType("bigint")
                        .HasColumnName("retry_delay_ticks");

                    b.Property<long?>("RobotsCrawlDelayMilliseconds")
                        .HasColumnType("bigint")
                        .HasColumnName("robots_crawl_delay_milliseconds");

                    b.Property<string>("SentETag")
                        .HasColumnType("text")
                        .HasColumnName("sent_etag");

                    b.Property<long?>("SentLastModifiedUtcTicks")
                        .HasColumnType("bigint")
                        .HasColumnName("sent_last_modified_utc_ticks");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_id");

                    b.HasKey("AttemptId");

                    b.HasIndex("CaptureSha256")
                        .HasDatabaseName("ix_collection_attempts_capture");

                    b.HasIndex("PriorCaptureAttemptId")
                        .HasDatabaseName("ix_collection_attempts_prior_capture_link");

                    b.HasIndex("AttemptId", "CaptureSha256")
                        .IsUnique()
                        .HasDatabaseName("ux_collection_attempts_id_capture");

                    b.HasIndex("SourceId", "ObservedAtUtcTicks", "AttemptId")
                        .HasDatabaseName("ix_collection_attempts_prior_capture")
                        .HasFilter("outcome = 'captured'");

                    b.ToTable("collection_attempts", null, t =>
                        {
                            t.HasCheckConstraint("ck_collection_attempts_identity", "length(btrim(attempt_id)) > 0 AND length(btrim(source_id)) > 0 AND length(btrim(requested_url)) > 0 AND length(btrim(final_url)) > 0");

                            t.HasCheckConstraint("ck_collection_attempts_observed_ticks", "observed_at_utc_ticks BETWEEN 0 AND 3155378975999999999");

                            t.HasCheckConstraint("ck_collection_attempts_outcome", "(outcome = 'captured' AND has_response AND response_status_code IS NOT NULL AND response_status_code = 200 AND capture_sha256 IS NOT NULL AND failure_code IS NULL AND retry_delay_ticks IS NULL AND prior_capture_attempt_id IS NULL AND prior_capture_sha256 IS NULL)\nOR (outcome = 'notModified' AND has_response AND has_sent_validators AND response_status_code IS NOT NULL AND response_status_code = 304 AND capture_sha256 IS NULL AND failure_code IS NULL AND retry_delay_ticks IS NULL)\nOR (outcome = 'failed' AND failure_code IS NOT NULL AND retry_delay_ticks IS NULL AND capture_sha256 IS NULL AND prior_capture_attempt_id IS NULL AND prior_capture_sha256 IS NULL)\nOR (outcome = 'deferred' AND failure_code IS NOT NULL AND capture_sha256 IS NULL AND prior_capture_attempt_id IS NULL AND prior_capture_sha256 IS NULL)");

                            t.HasCheckConstraint("ck_collection_attempts_prior_outcome", "prior_capture_attempt_id IS NULL OR (outcome = 'notModified' AND prior_capture_attempt_id <> attempt_id)");

                            t.HasCheckConstraint("ck_collection_attempts_prior_pair", "(prior_capture_attempt_id IS NULL) = (prior_capture_sha256 IS NULL)");

                            t.HasCheckConstraint("ck_collection_attempts_response", "(has_response AND response_status_code IS NOT NULL AND response_status_code BETWEEN 100 AND 599 AND response_content_encodings IS NOT NULL AND array_position(response_content_encodings, NULL) IS NULL)\nOR (NOT has_response AND response_status_code IS NULL AND response_etag IS NULL AND response_last_modified_utc_ticks IS NULL AND response_content_type IS NULL AND response_content_encodings IS NULL)");

                            t.HasCheckConstraint("ck_collection_attempts_response_ticks", "response_last_modified_utc_ticks IS NULL OR response_last_modified_utc_ticks BETWEEN 0 AND 3155378975999999999");

                            t.HasCheckConstraint("ck_collection_attempts_retry_ticks", "retry_delay_ticks IS NULL OR retry_delay_ticks >= 0");

                            t.HasCheckConstraint("ck_collection_attempts_robots_delay", "robots_crawl_delay_milliseconds IS NULL OR robots_crawl_delay_milliseconds BETWEEN 0 AND 922337203685000");

                            t.HasCheckConstraint("ck_collection_attempts_sent_ticks", "sent_last_modified_utc_ticks IS NULL OR sent_last_modified_utc_ticks BETWEEN 0 AND 3155378975999999999");

                            t.HasCheckConstraint("ck_collection_attempts_validators", "(has_sent_validators OR (sent_etag IS NULL AND sent_last_modified_utc_ticks IS NULL))");
                        });
                });

            modelBuilder.Entity("CivicLens.Infrastructure.Collection.Persistence.CaptureRow", b =>
                {
                    b.Property<string>("Sha256")
                        .HasColumnType("text")
                        .HasColumnName("sha256");

                    b.Property<long>("ByteLength")
                        .HasColumnType("bigint")
                        .HasColumnName("byte_length");

                    b.HasKey("Sha256");

                    b.ToTable("collection_captures", null, t =>
                        {
                            t.HasCheckConstraint("ck_collection_captures_byte_length", "byte_length >= 0");

                            t.HasCheckConstraint("ck_collection_captures_sha256", "sha256 ~ '^[0-9a-f]{64}$'");
                        });
                });

            modelBuilder.Entity("CivicLens.Infrastructure.Documents.Persistence.DocumentExtractionRow", b =>
                {
                    b.Property<string>("ExtractionId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("extraction_id");

                    b.Property<string>("AttemptId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("attempt_id");

                    b.Property<string>("NormalizationVersion")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("normalization_version");

                    b.Property<string>("ParserVersion")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("parser_version");

                    b.Property<string>("ProfileJson")
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)")
                        .HasColumnName("profile_json");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<string>("TextSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("text_sha256");

                    b.HasKey("ExtractionId");

                    b.HasIndex("AttemptId")
                        .HasDatabaseName("ix_document_extractions_attempt");

                    b.ToTable("document_extractions", null, t =>
                        {
                            t.HasCheckConstraint("ck_document_extractions_hashes", "extraction_id ~ '^[0-9a-f]{64}$' AND text_sha256 ~ '^[0-9a-f]{64}$'");

                            t.HasCheckConstraint("ck_document_extractions_text_limit", "length(text) <= 2000000");

                            t.HasCheckConstraint("ck_document_extractions_versions", "length(btrim(parser_version)) > 0 AND length(btrim(normalization_version)) > 0");
                        });
                });

            modelBuilder.Entity("CivicLens.Infrastructure.Collection.Discovery.DiscoveryAdmissionBatchRow", b =>
                {
                    b.HasOne("CivicLens.Infrastructure.Collection.Discovery.DiscoveryRow", null)
                        .WithMany()
                        .HasForeignKey("AttemptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CivicLens.Infrastructure.Collection.Discovery.DiscoveryCandidateJobRow", b =>
                {
                    b.HasOne("CivicLens.Infrastructure.Collection.Jobs.Persistence.JobRow", null)
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CivicLens.Infrastructure.Collection.Discovery.DiscoveryRow", b =>
                {
                    b.HasOne("CivicLens.Infrastructure.Collection.Persistence.AttemptRow", null)
                        .WithOne()
                        .HasForeignKey("CivicLens.Infrastructure.Collection.Discovery.DiscoveryRow", "AttemptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CivicLens.Infrastructure.Collection.Jobs.Persistence.CollectorSlotRow", b =>
                {
                    b.HasOne("CivicLens.Infrastructure.Collection.Jobs.Persistence.JobAttemptRow", null)
                        .WithMany()
                        .HasForeignKey("AttemptId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CivicLens.Infrastructure.Collection.Jobs.Persistence.JobRow", null)
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("CivicLens.Infrastructure.Collection.Jobs.Persistence.JobAttemptRow", b =>
                {
                    b.HasOne("CivicLens.Infrastructure.Collection.Jobs.Persistence.JobRow", null)
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CivicLens.Infrastructure.Collection.Jobs.Persistence.JobOriginRow", b =>
                {
                    b.HasOne("CivicLens.Infrastructure.Collection.Jobs.Persistence.JobAttemptRow", null)
                        .WithMany()
                        .HasForeignKey("UnresolvedAttemptId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("CivicLens.Infrastructure.Collection.Persistence.AttemptRow", b =>
                {
                    b.HasOne("CivicLens.Infrastructure.Collection.Persistence.CaptureRow", null)
                        .WithMany()
                        .HasForeignKey("CaptureSha256")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CivicLens.Infrastructure.Collection.Persistence.AttemptRow", null)
                        .WithMany()
                        .HasForeignKey("PriorCaptureAttemptId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("CivicLens.Infrastructure.Documents.Persistence.DocumentExtractionRow", b =>
                {
                    b.HasOne("CivicLens.Infrastructure.Collection.Persistence.AttemptRow", null)
                        .WithMany()
                        .HasForeignKey("AttemptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
