<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>Exe</OutputType></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../CivicLens.Application/CivicLens.Application.csproj" />
    <ProjectReference Include="../CivicLens.Infrastructure/CivicLens.Infrastructure.csproj" />
  </ItemGroup>
</Project>
