<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup><OutputType>Exe</OutputType></PropertyGroup>
  <ItemGroup>
    <Content Update="wwwroot/**" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="wwwroot/css/theme.css" LogicalName="assets/theme.css" />
    <EmbeddedResource Include="wwwroot/preview.css" LogicalName="assets/preview.css" />
    <EmbeddedResource Include="wwwroot/diff.css" LogicalName="assets/diff.css" />
    <EmbeddedResource Include="wwwroot/public.css" LogicalName="assets/public.css" />
    <EmbeddedResource Include="wwwroot/diff.js" LogicalName="assets/diff.js" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" Version="10.0.12" />
    <ProjectReference Include="../CivicLens.Application/CivicLens.Application.csproj" />
    <ProjectReference Include="../CivicLens.Infrastructure/CivicLens.Infrastructure.csproj" />
  </ItemGroup>
</Project>
