<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup><OutputType>Exe</OutputType></PropertyGroup>
  <ItemGroup>
    <Content Update="wwwroot/**" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="wwwroot/css/theme.css" LogicalName="assets/css/theme.css" />
    <EmbeddedResource Include="wwwroot/css/app.css" LogicalName="assets/css/app.css" />
    <EmbeddedResource Include="wwwroot/js/theme.js" LogicalName="assets/js/theme.js" />
    <EmbeddedResource Include="wwwroot/js/app.js" LogicalName="assets/js/app.js" />
    <EmbeddedResource Include="wwwroot/fonts/instrument-sans.woff2" LogicalName="assets/fonts/instrument-sans.woff2" />
    <EmbeddedResource Include="wwwroot/fonts/newsreader.woff2" LogicalName="assets/fonts/newsreader.woff2" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" Version="10.0.12" />
    <ProjectReference Include="../CivicLens.Application/CivicLens.Application.csproj" />
    <ProjectReference Include="../CivicLens.Infrastructure/CivicLens.Infrastructure.csproj" />
  </ItemGroup>
</Project>
